### PR TITLE
Minor change to the regexp so it now works with multiple answers in a…

### PR DESCRIPTION
**Pull request by hugueslacroix**
Minor change to the regexp so it now works with multiple answers in a single text

### CODE REVIEW

**Comment by rivasd** [comment]
oups! forgot about the global flag! sorry :)

**Comment by rivasd** [comment]
Hey @hugueslacroix , could you change this pull request so that it targets my `parallelport` branch? this way your changes will be included in the real jsPsych repo when i fix some other things :) (I'll merge them back to UQAM no worries)

**Comment by hugueslacroix** [comment]
@rivasd: I'm not sure I did the right thing ... did I?

**Comment by rivasd** [comment]
hum nope ! but thats my fault. nvm, change it back to uqam

**Comment by rivasd** [comment]
I'll `git cherry-pick` only the relevant commits into my `parallelport` branch myself

**Pull request merged**
